# Generated by Django 4.0.5 on 2022-06-19 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Moniurl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=100)),
                ('isAPI', models.BooleanField()),
                ('repeatAfter', models.IntegerField()),
                ('httpMethod', models.CharField(max_length=10)),
                ('url', models.CharField(max_length=100)),
                ('authReq', models.BooleanField()),
                ('bearer', models.CharField(blank=True, max_length=100)),
                ('entered_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_url', models.CharField(max_length=100)),
                ('status_code', models.IntegerField()),
                ('content_length', models.IntegerField()),
                ('time_taken', models.DecimalField(decimal_places=7, max_digits=19)),
                ('content_type', models.CharField(max_length=30)),
                ('url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moni_url', to='monito_api.moniurl')),
            ],
        ),
    ]
