# Generated by Django 4.0.5 on 2022-06-19 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
