# Generated by Django 4.0.5 on 2022-06-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0002_rename_logs_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='moniurl',
            name='JSONbody',
            field=models.JSONField(default={}),
        ),
    ]
