# Generated by Django 4.0.5 on 2022-06-20 03:23

from django.db import migrations, models
import monito_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0003_moniurl_jsonbody'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moniurl',
            name='JSONbody',
            field=models.JSONField(default=monito_api.models.Moniurl.JSON_default),
        ),
    ]
