# Generated by Django 4.0.5 on 2022-06-20 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0004_alter_moniurl_jsonbody'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='entered_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
