# Generated by Django 4.0.5 on 2022-07-22 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0006_moniurl_failedcount_moniurl_laststatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moniurl',
            old_name='lastStatus',
            new_name='lastErrorStatus',
        ),
    ]
