# Generated by Django 4.0.5 on 2022-07-22 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0007_rename_laststatus_moniurl_lasterrorstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moniurl',
            name='lastErrorStatus',
        ),
    ]
