# Generated by Django 4.0.5 on 2022-07-22 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monito_api', '0008_remove_moniurl_lasterrorstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='moniurl',
            name='alertThreshold',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
